/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "power.h"
#include <math.h>

int *
power_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("power(%d, %d) is called\n",argp->a, argp->b);
	result = (argp->a * argp->b);

	return &result;
}
